# 테스트용
steps:
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Cloud Build OK"
        echo "BRANCH=$$BRANCH_NAME COMMIT=$$COMMIT_SHA"
        date -u

# 커스텀 SA 사용 시 로그 버킷 대신 Cloud Logging만 사용
options:
  logging: CLOUD_LOGGING_ONLY
